import { prisma } from "@/lib/prisma";
import { PUBLISH_BUILTIN_BASE_DOMAIN } from "@/lib/publish-host";

const MAX_OVERRIDE_CHARS = 48_288;

/** Предпочтительный канонический origin проекта для подсказок в UI (HTTPS). */
export async function resolveProjectPublicOrigin(projectId: string): Promise<string | null> {
  const verified = await prisma.publishDomainBinding.findFirst({
    where: {
      projectId,
      isActive: true,
      verificationStatus: "VERIFIED",
    },
    orderBy: { verifiedAt: "desc" },
    select: { host: true },
  });
  if (verified?.host) {
    const h = verified.host.trim().toLowerCase();
    return h ? `https://${h.replace(/^\/*/, "").split("/")[0]}` : null;
  }
  const proj = await prisma.project.findUnique({
    where: { id: projectId },
    select: { subdomain: true },
  });
  const sub = proj?.subdomain?.trim();
  if (!sub) return null;
  return `https://${sub}.${PUBLISH_BUILTIN_BASE_DOMAIN}`;
}

function normalizeRobotsBody(text: string): string {
  return text.replace(/\r\n/g, "\n").trimEnd();
}

/** Публичные страницы с noindex → строки Disallow в robots.txt. Корень сайта («/») не трогаем: Disallow:/ заблокирует всё дерево. */
export function disallowPathForPublishedNoIndexPage(path: string): string | null {
  const raw = typeof path === "string" ? path.trim() : "";
  if (!raw || raw === "/") return null;
  let p = raw.startsWith("/") ? raw : `/${raw}`;
  while (p.length > 1 && p.endsWith("/")) p = p.slice(0, -1);
  return `Disallow: ${p}`;
}

export async function buildAutoRobotsTxtForSite(siteId: string): Promise<string> {
  const lines: string[] = ["# Generated by Lemnity CMS", "User-agent: *", "Allow: /"];

  const candidates = await prisma.cmsPage.findMany({
    where: { siteId, publishedRevisionId: { not: null }, noIndex: true },
    select: { path: true },
  });
  const disallows = new Set<string>();
  for (const c of candidates) {
    const rule = disallowPathForPublishedNoIndexPage(c.path ?? "");
    if (rule) disallows.add(rule);
  }
  const sorted = Array.from(disallows).sort((a, b) => a.localeCompare(b));
  lines.push(...sorted);
  lines.push("");
  return lines.join("\n");
}

/** Текущий сохранённый override (до MAX_OVERRIDE_CHARS символов) или отклонено. */
export function normalizeStoredRobotsOverride(raw: string | null | undefined): string | null {
  if (typeof raw !== "string") return null;
  const t = raw.replace(/\r\n/g, "\n").trimEnd();
  if (!t.trim()) return null;
  return t.length > MAX_OVERRIDE_CHARS ? null : t;
}

/** Эффективный robots.txt для проекта CMS: override или автогенерация. Без сайта CMS — простой Allow. */
export async function resolveRobotsTxtForProject(projectId: string): Promise<string> {
  const site = await prisma.cmsSite.findUnique({
    where: { projectId },
    select: { id: true, robotsTxtOverride: true },
  });

  const minimal = (): string =>
    normalizeRobotsBody(["User-agent: *", "Allow: /"].join("\n")) + "\n";

  if (!site) return minimal();

  const overrideRaw = typeof site.robotsTxtOverride === "string" ? site.robotsTxtOverride : null;
  const override = normalizeStoredRobotsOverride(overrideRaw);
  if (override) return normalizeRobotsBody(override) + "\n";

  const generated = normalizeRobotsBody(await buildAutoRobotsTxtForSite(site.id)) + "\n";
  return generated;
}
